# -*- coding: utf-8 -*-
"""volume_of_sphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIeNklK3kIPkvi1RyBjTsgLHxHcPJPkW
"""

import math
def calculate_volume_of_sphere(radius):
  volume = (4/3) * math.pi * (radius ** 3)
  return volume

print(calculate_volume_of_sphere(30))
print(calculate_volume_of_sphere(40))